kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "kafka-bench-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/jihed/openshift-jmeter-kafka.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile
